      INTERFACE MPI_BCAST

	  SUBROUTINE MPI_BCAST_C(BUFFER, COUNT, DATATYPE, ROOT, COMM,
     &    IERROR) 
        CHARACTER*(*), INTENT(INOUT) :: BUFFER
          INTEGER, INTENT(IN)  :: COUNT
          INTEGER, INTENT(IN)  :: DATATYPE
          INTEGER, INTENT(IN)  :: ROOT
          INTEGER, INTENT(IN)  :: COMM
          INTEGER, INTENT(OUT) :: IERROR 

      END SUBROUTINE  MPI_BCAST_C

	  SUBROUTINE MPI_BCAST_I4(BUFFER, COUNT, DATATYPE, ROOT, COMM,
     &	IERROR) 
          INTEGER(4), INTENT(INOUT) :: BUFFER
          INTEGER, INTENT(IN)  :: COUNT
          INTEGER, INTENT(IN)  :: DATATYPE
          INTEGER, INTENT(IN)  :: ROOT
          INTEGER, INTENT(IN)  :: COMM
          INTEGER, INTENT(OUT) :: IERROR 

      END SUBROUTINE  MPI_BCAST_I4

	  END INTERFACE MPI_BCAST
