#!/bin/bash
echo "PC name:"
who

echo "IP adress:"
hostname -i 

echo "Names of registered users:"
cut -d: -f1 /etc/passwd | head -5
echo "________________________________________________________________"



echo "Menu"

PS3="Select the operation: "
options=("Show all information about catalogs"
	 "Edit file permission"
	 "Exit")

select opt in "${options[@]}";
 do

  case $opt in
    "Show all information about catalogs")
	clear
        echo "Operatin 1"
	echo "________________________________"
	echo "Input directory name"
	read name
	ls /home/ikrut0nardo/$name
	read -p "Press [enter] to continue"
	clear
      ;;
    "Edit file permission")
	clear
        echo "Operation 2"
	echo "________________________________"
	cd /home/ikrut0nardo/lab3
	ls
	echo "Input file name"
	read name
	echo "Input permission options"
	read par
	chmod $par $name
	ls -l $name
	read -p "Press [enter] to continue" 
	clear
      ;;
    "Exit")
      break
      ;;
    *) 
      echo "Invalid option $REPLY"
      ;;
  esac
done
